env:
  VARIABLE_NAME: 'valeur de ma variable'

name: Mon premier workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files
        run: ls -al
      - name: Afficher une variable
        env:
          VARIABLE_NAME: un autre variable
        run: echo ${{ env.VARIABLE_NAME }}
